version: 2.1

orbs:
  orb-tools: circleci/orb-tools@3.0.0

executors:
  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli
  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml

workflows:
  verify:
    jobs:
      - lint
      - validate
      - orb-tools/test-in-builds:
          name: test
          orb-location: src/@orb.yml
          orb-name: vm-install
          test-steps:
            - vm-install/install-java11
            - vm-install/install-gradle
            - vm-install/install-docker-compose
            - run: |
                java --version
                gradle --version
                docker-compose --version
