version: 2.1

orbs:
  orb-tools: circleci/orb-tools@3.0.0

executors:
  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

workflows:
  verify:
    jobs:
      - lint
      - orb-tools/validate:
          name: validate
          orb-path: src/@orb.yml
      - orb-tools/test-in-builds:
          name: test
          orb-location: src/@orb.yml
          orb-name: vm-install-tools
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/install-test.yml
          requires:
            - validate
            - lint
      - orb-tools/publish:
          name: publish
          filters:
            branches:
              ignore: master
          orb-path: src/@orb.yml
          orb-ref: entur/vm-install-tools@dev:$CIRCLE_BRANCH
          requires:
            -test
      - orb-tools/increment:
          name: release
          filters:
            branches:
              only: master
          orb-path: src/@orb.yml
          orb-ref: entur/vm-install-tools
          requires:
            -test
